// THE SUPPORT QUEUE: what players (and playtesters) tried that the game couldn't do, clustered by
// capability and ranked by demand. Items close themselves when a later probe finds them supported.
//
// Storage is injected (a JSON file from the CLI, localStorage in the browser), so the same queue
// logic runs in both.

import type { ProbeResult } from './playtest.js';

export interface QueueItem {
  capability: string;
  status: 'open' | 'supported';
  kind: 'unsupported' | 'misread' | 'mixed';
  demand: number;          // failed attempts
  passes: number;          // attempts that succeeded (after support landed, or partially)
  strategies: string[];
  examples: Array<{ text: string; stage: string; outcome: string }>;
  firstSeen: string; lastSeen: string;
}

export interface QueueData { version: 1; items: Record<string, QueueItem>; runs: number; }

export class SupportQueue {
  data: QueueData;
  constructor(data?: QueueData | null) { this.data = data && data.version === 1 ? data : { version: 1, items: {}, runs: 0 }; }

  /** Fold one probe pass in. Unreachable results say nothing about capability. */
  fold(results: ProbeResult[], stage: string, when = new Date().toISOString().slice(0, 10)): void {
    for (const r of results) {
      if (r.status === 'unreachable') continue;
      const key = r.atom.capability;
      const it = (this.data.items[key] ??= { capability: key, status: 'open', kind: 'unsupported', demand: 0, passes: 0, strategies: [], examples: [], firstSeen: when, lastSeen: when });
      if (!it.strategies.includes(r.atom.strategy)) it.strategies.push(r.atom.strategy);
      it.lastSeen = when;
      if (r.status === 'supported') { it.passes++; continue; }
      it.demand++;
      const kind = r.status === 'misread' ? 'misread' : 'unsupported';
      it.kind = it.demand === 1 ? kind : it.kind === kind ? kind : 'mixed';
      const outcome = r.status === 'misread' ? `misread as ${r.got}` : `refused: ${r.reason}`;
      if (it.examples.length < 6 && !it.examples.some((e) => e.text === r.atom.text)) it.examples.push({ text: r.atom.text, stage, outcome });
    }
    // status follows the latest attempts: all passing closes an item, any failing (re)opens it
    const byCap = new Map<string, ProbeResult[]>();
    for (const r of results) if (r.status !== 'unreachable') (byCap.get(r.atom.capability) ?? byCap.set(r.atom.capability, []).get(r.atom.capability)!).push(r);
    for (const [cap, rs] of byCap) this.data.items[cap].status = rs.every((r) => r.status === 'supported') ? 'supported' : 'open';
    this.data.runs++;
  }

  ranked(): QueueItem[] {
    return Object.values(this.data.items).filter((i) => i.status === 'open').sort((a, b) => b.demand * b.strategies.length - a.demand * a.strategies.length);
  }

  toMarkdown(): string {
    const open = this.ranked();
    const done = Object.values(this.data.items).filter((i) => i.status === 'supported');
    const row = (i: QueueItem, n: number) => `| ${n} | \`${i.capability}\` | ${i.kind} | ${i.demand} | ${i.strategies.join(', ')} | ${i.examples.slice(0, 2).map((e) => `“${e.text}” → ${e.outcome}`).join('<br>')} |`;
    return [
      '# Support queue',
      '',
      '> Generated by `bun test/playtest.mjs`. What playtesters tried that the rules could not do, clustered by',
      '> capability and ranked by demand × breadth (how many different strategies wanted it). **misread** = the',
      '> parser picked the wrong action (it thought it understood); **unsupported** = no reading at all.',
      '> Items close automatically when a later probe finds them supported.',
      '',
      `Probe passes folded in: ${this.data.runs}. Open: ${open.length}. Supported: ${done.length}.`,
      '',
      '| # | capability | kind | demand | wanted by | examples |',
      '|---|---|---|---|---|---|',
      ...open.map((i, n) => row(i, n + 1)),
      '',
      '## Supported (closed)',
      '',
      done.map((i) => `\`${i.capability}\``).join(' · ') || '—',
      '',
    ].join('\n');
  }
}
